services:
  # ============================================================================
  # FRONTEND
  # ============================================================================
  frontend-service:
    container_name: frontend-service
    build:
      context: .
      dockerfile: services/frontend-service/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PUBLIC_DOMAIN=${DOMAIN}
      - PUBLIC_CLIENT_ID=${OAUTH_CLIENT_ID}
      - PUBLIC_OAUTH_REDIRECT_URI=${OAUTH_REDIRECT}
    networks:
      - transcendence-internal
    ports:
      - "5173:5173"
    volumes:
      - ./services/frontend-service/src:/app/services/frontend-service/src
      - ./services/frontend-service/static:/app/services/frontend-service/static
      - ./services/frontend-service/package.json:/app/services/frontend-service/package.json:ro
      - ./services/frontend-service/tsconfig.json:/app/services/frontend-service/tsconfig.json:ro
      - ./services/frontend-service/svelte.config.js:/app/services/frontend-service/svelte.config.js:ro
      - ./services/frontend-service/vite.config.ts:/app/services/frontend-service/vite.config.ts:ro
    depends_on:
      backend-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # ============================================================================
  # BACKEND SERVICES
  # ============================================================================

  backend-service:
    container_name: backend-service
    build:
      context: ./services/backend-service
      dockerfile: Dockerfile.dev
    env_file:
      - ./services/backend-service/src/.env
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_REDIRECT=${OAUTH_REDIRECT}
      - APP_FRONTEND_URL=${DOMAIN}
      - BUILD=DEV
      - BACKEND_INTERNAL_API_KEY=${BACKEND_INTERNAL_API_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URI=http://${DOMAIN}/auth/callback/github
      - INTRA_CLIENT_ID=${INTRA_CLIENT_ID}
      - INTRA_CLIENT_SECRET=${INTRA_CLIENT_SECRET}
      - INTRA_REDIRECT_URI=http://${DOMAIN}/auth/callback/intra
    networks:
      - transcendence-internal
    ports:
      - "4000:4000"
    volumes:
      - ./services/backend-service/src:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/up"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  game-service:
    container_name: game-service
    build:
      context: .
      dockerfile: services/game-service/Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - INTERNAL_WS_PORT=3002
      - PUBLIC_WS_PORT=3003
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
    networks:
      - transcendence-internal
    ports:
      - "3002:3002" # internal
      - "3003:3003" # external
    volumes:
      - ./services/game-service/src:/app/services/game-service/src
      - ./packages/game-ws-protocol/src:/app/packages/game-ws-protocol/src
    depends_on:
      - backend-service
    restart: unless-stopped

  # ============================================================================
  # INFRASTRUCTURE
  # ============================================================================
  gateway:
    container_name: gateway
    image: traefik:v3.2
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    networks:
      - transcendence-internal
    ports:
      - "8080:80"
      - "8443:443"
      - "127.0.0.1:8081:8080"
    volumes:
      - ./services/gateway/conf/dev/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./services/gateway/conf/dev:/etc/traefik/conf:ro
      - ./certs:/certs:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/ping",
        ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - transcendence-internal
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./services/mariadb/conf/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./services/mariadb/conf/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

# ==============================================================================
# VOLUMES
# ==============================================================================
volumes:
  mariadb_data:
    driver: local

# ==============================================================================
# NETWORKS
# ==============================================================================
networks:
  transcendence-internal:
    driver: bridge
